### ISSUE TITLE
Social share events not being sent to analytics 

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/servicenow#123]
If you go on https://www.servicenow.com/blogs/2023/3-ways-enhance-digital-experiences.html , Accept Cookies and then click on social share to facebook, you will see outgoing requests where the payload contains the same information as in the event. for our page https://feat-analytics--servicenow--hlxsites.hlx.live/blogs/2023/3-ways-enhance-digital-experiences this doesn't happen and I'm wondering why... you can still merge this PR, but it would be good to understand why are the requests not firing. These requests seem to come from scripts in Launch, which we already have added on the pages.

**Comment by andreituicu** [comment]
The ServiceNow Analytics team confirmed that the way we push the events into the data layer is correct and they are investigating on their side why the events are not being sent to analytics.
