### ISSUE TITLE
Import links to subdomains of servicenow.com

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/servicenow#124]
Whem importing the blog articles the domains of links pointing to subdomains of`servicenow.com` are replaced with `www.servicenow.com`. 

See: https://www.servicenow.com/blogs/2022/3-trends-driving-mobile-app-adoption.html

**Comment by andreituicu** [comment]
Fixed in 563361fc4009f4ea00b223d467953cc7cafffb34
