### ISSUE TITLE
[Block] Quote 

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#13]
Implement and style quote block with variants.

Examples from the website:
* https://www.servicenow.com/blogs/2023/quickly-get-started-generative-ai.html
* https://www.servicenow.com/blogs/2023/delivering-promise-innovation.html
* https://www.servicenow.com/blogs/2023/put-humans-loop-generative-ai.html
https://www.servicenow.com/blogs/2023/better-employee-onboarding-day-1.html

Check on more blog pages to see if we have more variants

<img width="640" alt="Screenshot 2023-10-15 at 15 25 06" src="https://github.com/hlxsites/servicenow/assets/3651689/b0b47019-f5ff-45d5-b570-d44a2cda4047">

<img width="641" alt="Screenshot 2023-10-15 at 15 25 35" src="https://github.com/hlxsites/servicenow/assets/3651689/34651c7e-f8c5-4217-88f8-2e511295f1cf">

**Comment by andreituicu** [comment]
On closer inspection those are actually images. 🙂

**Comment by Obikaviola** [comment]
Can it be assigned to me?
