### ISSUE TITLE
Bibtext formating

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/servicenow#131]
The following article (https://www.servicenow.com/blogs/2022/data-augmentation-intent-classification.html) contains bibtext paragraph which needs to be properly formated. 

<img width="788" alt="image" src="https://github.com/hlxsites/servicenow/assets/22545805/3610f6ce-2a56-49a3-b926-1ed60b88520b">

**Comment by andreituicu** [comment]
Manually fixed in that particular word document.
