### ISSUE TITLE
Year page formatting

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/servicenow#135]
- card images are smaller than in the original 
- in the original page, thrends and research only contain two entries
- article order (for the year) is different from original

Origina: https://www.servicenow.com/blogs/2022.html
EDS: https://main--aemeds--servicenow-martech.hlx.live/blogs/2022

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113.6">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'; min-height: 15.0px}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #9a9a9a #9a9a9a #9a9a9a #9a9a9a; padding: 1.0px 5.0px 1.0px 5.0px}
</style>
</head>
<body>
<p class="p1"><br></p>
<p class="p1"><br></p>

https://www.servicenow.com/blogs/2022.html | https://main--aemeds--servicenow-martech.hlx.live/blogs/2022
-- | --

</body>
</html>

**Comment by andreituicu** [comment]
> in the original page, thrends and research only contain two entries

This has been discussed with the servicenow team and approved. They want 3 entries on all pages. https://github.com/hlxsites/servicenow/issues/99

**Comment by andreituicu** [comment]
> article order (for the year) is different from original

This is something we can discuss with them, we are sorting based on publication date, which seems correct to me.
