### ISSUE TITLE
Ordered list styling removes the ordering 

### ISSUE THREAD

**Issue by sunidhiazad** [hlxsites/servicenow#137]
Original: https://www.servicenow.com/blogs/2022/integrating-elevate-customer-loyalty.html
EDS: https://main--aemeds--servicenow-martech.hlx.live/blogs/2022/integrating-elevate-customer-loyalty

**Comment by andreituicu** [comment]
The list is correctly imported as `<ol>` ordered list, but this styling makes it so they all appear as as unordered: https://github.com/hlxsites/servicenow/blob/main/styles/styles.css#L202 . CC @benpeter
