### ISSUE TITLE
Superscript exponent in headings appearing inline

### ISSUE THREAD

**Issue by sunidhiazad** [hlxsites/servicenow#140]
Original: https://www.servicenow.com/blogs/2022/matching-ukrainian-refugees-us-sponsors.html
EDS: https://main--aemeds--servicenow-martech.hlx.live/blogs/2022/matching-ukrainian-refugees-us-sponsors

<img width="872" alt="Screenshot 2023-11-28 at 15 59 41" src="https://github.com/hlxsites/servicenow/assets/9343296/ecb8c757-441f-43f4-8ea5-badeeb1058b8">

<img width="814" alt="Screenshot 2023-11-28 at 15 59 50" src="https://github.com/hlxsites/servicenow/assets/9343296/784322d5-0351-4cd6-84d8-c6913ac22f21">

**Comment by sunidhiazad** [comment]
`<sup>1</sup>` not handled in importer

**Comment by sunidhiazad** [comment]
I only saw this issue in one page and I confirmed just now that the styling works when using superscript in document. If it is only seen once, we can fix it in the document by hand. @andreituicu

**Comment by andreituicu** [comment]
Manually fixed in the word document.
