### ISSUE TITLE
Bulleted list widely spaced out compared to the compact original

### ISSUE THREAD

**Issue by sunidhiazad** [hlxsites/servicenow#142]
Original: https://www.servicenow.com/blogs/2022/welcome-to-knowledge.html
EDS: https://main--aemeds--servicenow-martech.hlx.live/blogs/2022/welcome-to-knowledge

**Comment by andreituicu** [comment]
same situation here: unless there is a clear pattern, I would not fix it for this 1 off example and let it use the standardised styling for lists.
