### ISSUE TITLE
unlinked URLs become links in EDS

### ISSUE THREAD

**Issue by benpeter** [hlxsites/servicenow#159]
https://www.servicenow.com/blogs/2022/proactive-support-operations.html
vs
https://main--aemeds--servicenow-martech.hlx.live/blogs/2022/proactive-support-operations
(just before the copyright)

![image (1)](https://github.com/hlxsites/servicenow/assets/398734/db21632d-98a9-4f0e-8a30-407ab29b013a)
![image (2)](https://github.com/hlxsites/servicenow/assets/398734/e8e0aa3f-478c-44fe-b4b9-a2b70734a7df)

**Comment by andreituicu** [comment]
As discussed privately, not sure if we need to fix this particular case. 🙂 yes, it is different than the original website, but I don't see it as an issue if those URLs are transformed into links on EDS.
