### ISSUE TITLE
Vertical distance between text when headings are wrapped around

### ISSUE THREAD

**Issue by sunidhiazad** [hlxsites/servicenow#164]
Original: https://www.servicenow.com/blogs/2023/why-process-mining-is-game-changer.html
EDS: https://main--aemeds--servicenow-martech.hlx.live/blogs/2023/why-process-mining-is-game-changer

<img width="817" alt="Screenshot 2023-12-05 at 15 54 50" src="https://github.com/hlxsites/servicenow/assets/9343296/4878f303-199a-46b8-bb2d-c7200fb2346d">

<img width="827" alt="Screenshot 2023-12-05 at 15 54 58" src="https://github.com/hlxsites/servicenow/assets/9343296/f5964409-d28f-447e-9014-408fc2ce3960">

@andreituicu I am not sure if this one is reported yet, I see you are working on some headings issue already. Please feel free to close this one if it's already handled.

**Comment by andreituicu** [comment]
@sunidhiazad didn't see it reported yet. thank you!

**Comment by sunidhiazad** [comment]
One more such page: https://main--aemeds--servicenow-martech.hlx.live/blogs/2023/what-does-servicenow-do
https://www.servicenow.com/blogs/2023/what-does-servicenow-do.html

**Comment by sunidhiazad** [comment]
You can also see there is a vertical spacing issue in the main blog heading as well when it is wrapped around.
Original: https://www.servicenow.com/blogs/2023/visibility-tames-indias-digital-elephant.html
EDS: https://main--aemeds--servicenow-martech.hlx.live/blogs/2023/visibility-tames-indias-digital-elephant

**Comment by andreituicu** [comment]
@sunidhiazad should be fixed now. can you please retest to confirm?
