### ISSUE TITLE
Search form is not correctly styled in the german blog header

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#176]
<img width="172" alt="Screenshot 2023-12-08 at 14 12 57" src="https://github.com/hlxsites/servicenow/assets/3651689/cbf323f3-07f8-48b0-b900-d8e562f5c40d">

<img width="176" alt="Screenshot 2023-12-08 at 14 17 43" src="https://github.com/hlxsites/servicenow/assets/3651689/835e37da-7736-407c-986f-819b81370bdb">

**Comment by sunidhiazad** [comment]
@andreituicu Can you elaborate a bit more about the issue? 
https://main--servicenow--hlxsites.hlx.live/de/blogs/2023/3-vorteile-von-ki-im-contact-cen
https://main--aemeds--servicenow-martech.hlx.live/uk/blogs/2023/generative-ai-in-emea
