### ISSUE TITLE
Import Content Diff

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#204]
Prior to the golive, import the content diff.

To get the content diff, checkout the importer page.
Go to `/tools/sitemaps` folder and do:
```
npm install
node app.mjs download_old
node app.mjs download_new
node app.mjs diff
```

This will give you the diff list of pages that need to be imported, based on the customer's sitemaps and our sitemap.

Ensure that for every page imported, you also created a new redirect: see <TODO>

**Comment by sergiucoman** [comment]
done

**Comment by andreituicu** [comment]
Keeping this open until the customer goes live, we'll have to do it periodically.

**Comment by andreituicu** [comment]
Done. ServiceNow went live.
