### ISSUE TITLE
Add Diff Redirects

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#205]
As part of the migration to AEM EDS, there is a change in the url from using `.html` to **extension-less lowercased urls**. (see #24) 

The `redirects.xls` already contains all redirects for imported pages.

We need to add the diff of redirects for the content imported in #204 .
**Make sure you keep the redirects marked with green as those are extra redirects, which are not related to the extension-less migration.**

You have two options:
**1. manually add the new redirects** for the pages imported in #204 
2. use the sitemaps cli tool to regenerate the full list and replace all of the ones below the rows marked with green.

```
npm install
node app.mjs download_old
node app.mjs download_new
node app.mjs redirects | pbcopy
paste into redirects.xls
```

**Comment by sergiucoman** [comment]
done

**Comment by andreituicu** [comment]
Keeping this open until the customer goes live, we'll have to do it periodically.

**Comment by andreituicu** [comment]
Done. ServiceNow went live.
