### ISSUE TITLE
.html extension

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#24]
Currently all blog URLs have the `.html` extension and franklin urls with the same path return 404 for them.
Since the blogs were shared on social media, we need to find a solution to make them work after the franklin migration.

We have a few options:
1. **CDN level redirect/rewrite**: The CDN can either redirect the request to the url without `.html` or it can rewrite the url on the fly
2. Client Side Redirect in the 404 handler https://github.com/hlxsites/servicenow/issues/25
3. Creating redirects for all the old blog pages in the `redirects.xls`. This would be ~2000 redirects. New pages would directly work with the new url type.

**Comment by andreituicu** [comment]
Awaiting customer decision. Options were presented to them.

**Comment by andreituicu** [comment]
The customer decided for option 3.

> 3. Creating redirects for all the old blog pages in the redirects.xls. This would be ~2000 redirects. New pages would directly work with the new url type.

**Comment by andreituicu** [comment]
We also need to ensure that the share this lib integration is properly setup to:
* Not loose the share counters prior to go live
* Not share to social media URLs that are not being redirected (with the `.html` extension) after go live.

**Comment by florentin** [comment]
redirects.xlsx updated and code added here: https://github.com/hlxsites/servicenow/tree/sardan-sitemap-tools/tools/sitemaps
