### ISSUE TITLE
404 Handler

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#25]
Implement 404 handler page:

https://www.servicenow.com/blogs/2023/maximize-efficiency-hyperautomaation.html
The 404 handler page looks to be quite complex, so we need to decide what is the best way to structure it.

**Comment by benpeter** [comment]
keeping open to look at options to tackle this on a CDN level

**Comment by andreituicu** [comment]
Pending CDN configuration on Service Now side.
