### ISSUE TITLE
Integrate Akamai RUM

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#35]
The customer seems to be using Akamai Boomerang.

Even if Edge Delivery already has integrated RUM, we need to understand this usecase and integrate it.

<img width="1152" alt="Screenshot 2023-10-20 at 16 20 59" src="https://github.com/hlxsites/servicenow/assets/3651689/1986a2db-869e-4156-a8b3-1ce680a3d89b">

**Comment by sergiucoman** [comment]
As per Akamai mPulse Boomerang is injected at the CDN level. Nothing to do in EDS.

**Comment by sergiucoman** [comment]
closing this issue as it is not required.
