### ISSUE TITLE
Integrate Akamai Service Worker

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#36]
In the head of the blog there is an Akamai script for adding `akam-sw.js`
https://techdocs.akamai.com/script-management/docs/service-worker-tools.

We need to understand the customer's usecase and add integrate it, if it is still required.

**Comment by sergiucoman** [comment]
As per Akamai mPulse Boomerang is injected at the CDN level. Nothing to do in EDS.

**Comment by sergiucoman** [comment]
closing this issue as it is not required.
