### ISSUE TITLE
Autoblock copyright

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/servicenow#54]
~Each blog article has a copyright. This could be autoblocked. 

`© 2020 ServiceNow, Inc. All rights reserved. ServiceNow, the ServiceNow logo, Now, and other ServiceNow marks are trademarks and/or registered trademarks of ServiceNow, Inc. in the United States and/or other countries. Other company names, product names, and logos may be trademarks of the respective companies with which they are associated.`

**Comment by benpeter** [comment]
the copyright seems to reflect the year the article was issued
