### ISSUE TITLE
[Topic Page] Include description in the blog list cards for Customer Stories Topic

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#81]
The customer stories topic https://www.servicenow.com/blogs/topics/customer-stories.html cards include the description of each article too.

Please also check if there are other places where this happens.

<img width="794" alt="Screenshot 2023-11-14 at 13 45 05" src="https://github.com/hlxsites/servicenow/assets/3651689/c64c8ab1-1409-4d85-9933-0ea8eb116600">

**Comment by sunidhiazad** [comment]
This happens only in the topic "Customer stories", confirmed.
