### ISSUE TITLE
h3 in main lacking divider line

### ISSUE THREAD

**Issue by benpeter** [hlxsites/servicenow#82]
servicenow.com:

<img width="801" alt="image" src="https://github.com/hlxsites/servicenow/assets/398734/f8abda0a-ebcd-42da-9ff2-ce406eab5dbe">

main:

<img width="802" alt="image" src="https://github.com/hlxsites/servicenow/assets/398734/bd92987a-7397-430d-bab8-c5cfe33ced8f">

**Comment by andreituicu** [comment]
Isn't this the same as https://github.com/hlxsites/servicenow/issues/51?

**Comment by benpeter** [comment]
duplicates #51
