### ISSUE TITLE
cards: fix font style on topic tag

### ISSUE THREAD

**Issue by benpeter** [hlxsites/servicenow#85]
servicenow.com:

<img width="297" alt="image" src="https://github.com/hlxsites/servicenow/assets/398734/0cb19b90-8b7f-44a8-ae72-c2f2df9c557f">

main:
<img width="310" alt="image" src="https://github.com/hlxsites/servicenow/assets/398734/f99a7156-d7fb-4392-89c3-44bb01811e19">

**Comment by andreituicu** [comment]
@benpeter I wanted to fix this one, because I implemented the cards, but I don't see the difference. Could you please help me see it?

**Comment by benpeter** [comment]
looking at the zoomed-in screenshots above, the typeface is a little richer (bolder? heavier?) on main than on servicenow.com?

**Comment by benpeter** [comment]
playing around a bit, I'd say it's lacking `-webkit-font-smoothing: antialiased;`

**Comment by benpeter** [comment]
I put in #105 for this @andreituicu
