### ISSUE TITLE
[ Blog Header] Implement and style Blog Header

### ISSUE THREAD

**Issue by andreituicu** [hlxsites/servicenow#9]
Implement and style the blog header, including adding the input box for search.
As possible inspiration for implementing this, we can use the nav pattern used for the website header.

- [ ] Authors must be able to edit the links and content of the header, as it has different information on different geosites.
- [ ] Blog header must be autoblocked on all pages
- [ ] Desktop

<img width="1187" alt="Screenshot 2023-10-15 at 15 01 23" src="https://github.com/hlxsites/servicenow/assets/3651689/4713c37c-73a5-43ef-bad4-21708b80cc1e">

- [ ] Mobile

<img width="490" alt="Screenshot 2023-10-15 at 15 01 45" src="https://github.com/hlxsites/servicenow/assets/3651689/11d0a4aa-eb29-4f5e-91a8-eb6004810f26">

<img width="505" alt="Screenshot 2023-10-15 at 15 01 50" src="https://github.com/hlxsites/servicenow/assets/3651689/664e9a3c-3b13-427b-ad46-e6cc4e415778">

**Comment by benpeter** [comment]
fixed by #45

**Comment by benpeter** [comment]
fixed in #45
